### ISSUE TITLE
Taskinator::Api::Processes fails when one of the classes doesn't exist any more

### ISSUE THREAD

**Issue by bguban** [virtualstaticvoid/taskinator#24]
**Describe the bug**
When I try to get a list of processes I get an error

```ruby
processes = Taskinator::Api::Processes.new
processes.first # persistence.rb:551:in `const_get': uninitialized constant Flows::EtfGraderFlow (NameError)
```

The things are that the class that is stored in Redis (`Flows::EtfGraderFlow`) doesn't exist anymore.

**Comment by virtualstaticvoid** [comment]
Hi @bguban

This issue has been resolved as your PR has been merged.
