### ISSUE TITLE
job method doesn't work properly

### ISSUE THREAD

**Issue by bguban** [virtualstaticvoid/taskinator#4]
Hi. I use Resque as a background job processor. I have a job
```
class BackgroundJob
  def self.perform
    # do staff
  end
end
```
and call it in taskinator as 
```
define_process do
  job BackgroundJob
end
```
but it raises an exception `ERROR: undefined method `perform'  for `#<BackgroundJob:0x00007f88db87b458>`.

Then I decided to check different variants. If I create an instance method `def perform(*args)` in that class taskinator calls it and args is a blank array (without `*args` it raises an error `ERROR: wrong number of arguments (given 1, expected 0)`). 

Then I tried to change my job from `class` to `module` and looks like not it works like specified in the documentation but the things are that I need `class` to be able to create an instance of the job. For example, https://github.com/quirkey/resque-status gem instantiates job class to store some variables in it.

Could you suggest any best practices for how to work with such cases?

**Comment by virtualstaticvoid** [comment]
This is a bug! It should work for `#perform` methods which don't take arguments.

All the instances of `#perform` method I've used _have_ taken arguments, so I'd never picked up the issue.

Furthermore the specs use `expect(...).to receive(:perform)` which don't fail when called with or without arguments, so it wasn't picked up there either.

I'll work on a fix.

**Comment by bguban** [comment]
What is about `.perform` method? It works only if I use `module BackgroundJob`, but it raises `ERROR: undefined method` if I use `class BackgroundJob`? 
Probably would be better to rely on `if job.respond_to?(:perform)` instead of `if job.instance_of?(Module)` here https://github.com/virtualstaticvoid/taskinator/blob/945ac10a0afc466e8a0d27b685d204b045290a6a/lib/taskinator/task.rb#L233

**Comment by virtualstaticvoid** [comment]
Hi @bguban 
I've created the [`noargsfix`](https://github.com/virtualstaticvoid/taskinator/tree/noargsfix) branch with the proposed fix.
Would you mind giving it a try to see whether it solves your issue.
Thanks.

**Comment by bguban** [comment]
Not entirely. The things are that https://github.com/quirkey/resque-status plugin assumes to have job classes. It creates the `.perform` class method and prepares an instance with specific arguments. https://github.com/virtualstaticvoid/taskinator/tree/noargsfix creates `job.new.perform` that skips this flow. 

Is it possible to check if the `job` has a `perform` class method and if it has then call it directly, otherwise create an instance and call perform on the instance?
```
        if job. respond_to?(:perform)
          # resque
          job.perform(*args)
        else
          # delayedjob and sidekiq
          job.new.perform(*args)
        end
```

**Comment by virtualstaticvoid** [comment]
I've changed the implementation as you suggested. 
Branch has been updated. Let me know if it's good and I'll merge #5 and release the updated gem.

**Comment by bguban** [comment]
It works. Thanks a lot :)
