### ISSUE TITLE
Debugging best practice

### ISSUE THREAD

**Issue by bguban** [virtualstaticvoid/taskinator#9]
Is there a simple way to find arguments that were passed to a job from the error that I see in resque cleaner? It's very important for debugging because sometimes the error occurs only for a specific set of arguments.

I made a script but I'm almost sure that should be simpler way
```
parts = "d2a477e2-ef70-49aa-a924-5305feb16d05:task:2df5229d-723d-4fe2-a713-ad8a0392f476:subprocess:task:8e65468b-5ff0-460c-ae27-1bc2b9b66009:subprocess:task:e94961ba-43ca-42eb-83ee-f90d6d0e8a26:subprocess:task:3e338ec2-a01f-4508-b68e-e2b2047f9b0a".split(':')
source = Taskinator::Api::Processes.new
parts.each_with_index do |part, idx|
  next if part.in?(['task', 'subprocess'])

  source = source.__getobj__ if source.is_a?(Taskinator::Persistence::LazyLoader)

  uuid = parts[0..idx].join(':')
  new_source = case source
               when Taskinator::Api::Processes
                 source.find { |p| p.uuid == uuid }
               when Taskinator::Process::Sequential
                 source.tasks.find { |t| t.uuid == uuid }
               when Taskinator::Task::SubProcess
                 source.sub_process.tasks { |t| t.uuid == uuid }
               # when Taskinator::Tasks
               #   source.to_a.find { |t| t.uuid == uuid }
               end

  new_source = new_source.to_a.find { |t| t.uuid == uuid } if new_source.is_a?(Taskinator::Tasks)

  break if new_source.nil?

  source = new_source
end

source.args
```
`parts` variable contains the line I see in the resque cleaner.

**Comment by virtualstaticvoid** [comment]
Hi @bguban 

Since you have the task identifier, it is possible to load the task object using the `fetch` method and inspecting the arguments, as follows:

```ruby
task_uuid = "..."
task = Taskinator::Task.fetch(task_uuid)
puts task.args
```

This assumes that the associated keys in Redis haven't expired or been removed via `Process#cleanup`.

**Comment by virtualstaticvoid** [comment]
I've made some small improvements to the `Taskinator::Api` module, to make it more intuitive for accessing processes and tasks for the purpose of inspecting them.

It now provides `Taskinator::Api.find_process` and `Taskinator::Api.find_task` methods.

See [Debugging](https://github.com/virtualstaticvoid/taskinator#debugging) section of the README.

**Comment by bguban** [comment]
That's amazing! Thanks a lot 🥇
